-- SimpleChat MySQL schema
CREATE DATABASE IF NOT EXISTS `simplechat` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE `simplechat`;

CREATE TABLE IF NOT EXISTS `messages` (
  `id` BIGINT PRIMARY KEY AUTO_INCREMENT,
  `nickname` VARCHAR(64) NOT NULL,
  `content` TEXT NOT NULL,
  `room_key` VARCHAR(128) NOT NULL DEFAULT 'public',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
